# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# # User.create(name: 'Leah', admin: true, email: 'leah@gmail.com')
# User.create(name: 'Dovid', admin: true, email: 'dovid@gmail.com')
#
Student.create(name: 'Linor',  email: 'Linor@gmail.com')
Student.create(name: 'Chaya',  email: 'Chaya@gmail.com')
Student.create(name: 'Rivky',  email: 'Rivky@gmail.com')
#
Subject.create(user_id: 6, name: 'Algebra')
Subject.create(user_id: 6, name: 'Geometry')
Subject.create(user_id: 6, name: 'Technology')

Subject.create(user_id: 3, name: 'PE')
Subject.create(user_id: 3, name: 'Gardening')
Subject.create(user_id: 3, name: 'Wood Work')
Subject.create(user_id: 2, name: 'History')
Subject.create(user_id: 2, name: 'Biology')
Subject.create(user_id: 2, name: 'Geography')


StudentsAssignment.create(student_id: 2, assignment_id: 1)
StudentsAssignment.create(student_id: 3, assignment_id: 1)
StudentsAssignment.create(student_id: 4, assignment_id: 1)
StudentsAssignment.create(student_id: 5, assignment_id: 1)
StudentsAssignment.create(student_id: 6, assignment_id: 1)
StudentsAssignment.create(student_id: 1, assignment_id: 2)

StudentsAssignment.create(student_id: 3, assignment_id: 2)
StudentsAssignment.create(student_id: 4, assignment_id: 2)
StudentsAssignment.create(student_id: 5, assignment_id: 2)
StudentsAssignment.create(student_id: 6, assignment_id: 2)
StudentsAssignment.create(student_id: 1, assignment_id: 3)
StudentsAssignment.create(student_id: 2, assignment_id: 3)
StudentsAssignment.create(student_id: 4, assignment_id: 3)
StudentsAssignment.create(student_id: 5, assignment_id: 3)
StudentsAssignment.create(student_id: 6, assignment_id: 3)
StudentsAssignment.create(student_id: 1, assignment_id: 4)
StudentsAssignment.create(student_id: 2, assignment_id: 4)
StudentsAssignment.create(student_id: 3, assignment_id: 4)

StudentsSubject.create(student_id: 1, subject_id: 10)
StudentsSubject.create(student_id: 2, subject_id: 10)
StudentsSubject.create(student_id: 3, subject_id: 10)
StudentsSubject.create(student_id: 4, subject_id: 10)
StudentsSubject.create(student_id: 5, subject_id: 10)
StudentsSubject.create(student_id: 6, subject_id: 10)
StudentsSubject.create(student_id: 1, subject_id: 11)
StudentsSubject.create(student_id: 2, subject_id: 11)
StudentsSubject.create(student_id: 3, subject_id: 11)
StudentsSubject.create(student_id: 4, subject_id: 11)
StudentsSubject.create(student_id: 5, subject_id: 11)
StudentsSubject.create(student_id: 6, subject_id: 11)
StudentsSubject.create(student_id: 1, subject_id: 12)
StudentsSubject.create(student_id: 2, subject_id: 12)
StudentsSubject.create(student_id: 3, subject_id: 12)
StudentsSubject.create(student_id: 4, subject_id: 12)
StudentsSubject.create(student_id: 5, subject_id: 12)
StudentsSubject.create(student_id: 6, subject_id: 12)
StudentsSubject.create(student_id: 1, subject_id: 13)
StudentsSubject.create(student_id: 2, subject_id: 13)
StudentsSubject.create(student_id: 3, subject_id: 13)
StudentsSubject.create(student_id: 4, subject_id: 13)
StudentsSubject.create(student_id: 5, subject_id: 13)
StudentsSubject.create(student_id: 6, subject_id: 13)
StudentsSubject.create(student_id: 1, subject_id: 14)
StudentsSubject.create(student_id: 2, subject_id: 14)
StudentsSubject.create(student_id: 3, subject_id: 14)
StudentsSubject.create(student_id: 4, subject_id: 14)
StudentsSubject.create(student_id: 5, subject_id: 14)
StudentsSubject.create(student_id: 6, subject_id: 14)

StudentsSubject.create(student_id: 1, subject_id: 15)
StudentsSubject.create(student_id: 2, subject_id: 15)
StudentsSubject.create(student_id: 3, subject_id: 15)
StudentsSubject.create(student_id: 4, subject_id: 15)
StudentsSubject.create(student_id: 5, subject_id: 15)
StudentsSubject.create(student_id: 6, subject_id: 15)
StudentsSubject.create(student_id: 1, subject_id: 16)
StudentsSubject.create(student_id: 2, subject_id: 16)
StudentsSubject.create(student_id: 3, subject_id: 16)
StudentsSubject.create(student_id: 4, subject_id: 16)
StudentsSubject.create(student_id: 5, subject_id: 16)
StudentsSubject.create(student_id: 6, subject_id: 16)
StudentsSubject.create(student_id: 1, subject_id: 17)
StudentsSubject.create(student_id: 2, subject_id: 17)
StudentsSubject.create(student_id: 3, subject_id: 17)
StudentsSubject.create(student_id: 4, subject_id: 17)
StudentsSubject.create(student_id: 5, subject_id: 17)
StudentsSubject.create(student_id: 6, subject_id: 17)
StudentsSubject.create(student_id: 1, subject_id: 18)
StudentsSubject.create(student_id: 2, subject_id: 18)
StudentsSubject.create(student_id: 3, subject_id: 18)
StudentsSubject.create(student_id: 4, subject_id: 18)
StudentsSubject.create(student_id: 5, subject_id: 18)
StudentsSubject.create(student_id: 6, subject_id: 18)



Assignment.create(subject_id: 11, assignment_type: "HW", name: "pg 45", notes: "review well!!!! work hard and see results")
Assignment.create(subject_id: 12, assignment_type: "Quiz", name: "pg 45", notes: "review well!!!! work hard and see results")
Assignment.create(subject_id: 13, assignment_type: "Project", name: "power point project", notes: "due tomorrow")
Assignment.create(subject_id: 11, assignment_type: "Quiz", name: "pg 45", notes: "due tomorrow")
Assignment.create(subject_id: 12, assignment_type: "HW", name: "pg 45", notes: "due tomorrow")
Assignment.create(subject_id: 13, assignment_type: "Test", name: "pg 45", notesgood test preparationTuesday")
Assignment.create(subject_id: 14, assignment_type: "HW", name: "pg 45", notesgood test preparationTuesday")
Assignment.create(subject_id: 15, assignment_type: "HW", name: "pg 45", notesgood test preparationTuesday")
Assignment.create(subject_id: 16, assignment_type: "HW", name: "pg 45", notesgood test preparationTuesday")
Assignment.create(subject_id: 17, assignment_type: "Test", name: "pg 45", notes: "due tomorrow")
Assignment.create(subject_id: 18, assignment_type: "HW", name: "pg 45", notes: "due tomorrow")
Assignment.create(subject_id: 18, assignment_type: "Project", name: "power point project", notes: "due tomorrow")
Assignment.create(subject_id: 17, assignment_type: "Test", name: "pg 45", notes: "good test preparation")
Assignment.create(subject_id: 16, assignment_type: "Quiz", name: "pg 45", notes: "good test preparation")
Assignment.create(subject_id: 15, assignment_type: "Test", name: "pg 45", notes: "good test preparation")
# Subject.create(user_id: 3, name: 'Soc Studies')
#
# Assignment.create(subject_id: 1, assignment_type: 'Test', name: 'pg 70', notes: 'review and study well')
# Assignment.create(subject_id: 2, assignment_type: 'HW', name: 'pg 39', notes: 'review well')
# Assignment.create(subject_id: 3, assignment_type: 'Project', name: 'pg 38', notes: 'review and study well')
# Assignment.create(subject_id: 4, assignment_type: 'HW', name: 'pg 40', notes: 'review well. Keep working for success.')
# Assignment.create(subject_id: 5, assignment_type: 'Quiz', name: 'pg 70', notes: 'review well. Will randomly test selected children')
# Assignment.create(subject_id: 6, assignment_type: 'Test', name: 'pg 78', notes: 'review well. Keep working for success.')
# Assignment.create(subject_id: 7, assignment_type: 'HW', name: 'pg 80', notes: 'review well. Will randomly test selected children')
# Assignment.create(subject_id: 1, assignment_type: 'Project', name: 'pg 830', notes: 'review and study well')
# Assignment.create(subject_id: 2, assignment_type: 'Test', name: 'pg 34', notes: 'review well. Will randomly test selected children')
# Assignment.create(subject_id: 3, assignment_type: 'Quiz', name: 'pg 40', notes: 'review well. Keep working for success.')
# Assignment.create(subject_id: 4, assignment_type: 'HW', name: 'pg 80', notes: 'review well')
# Assignment.create(subject_id: 5, assignment_type: 'Project', name: 'pg 34', notes: 'Study well for upcoming test. Will randomly test selected children')
# Assignment.create(subject_id: 6, assignment_type: 'Project', name: 'pg 39', notes: 'Study well for upcoming test. Will randomly test selected children')
